apiVersion: v1
kind: Pod
metadata: 
  name: balaji-pod
  labels:
     name: balaji
     type: frontend
spec:
  containers:
  - name: balaji
    image: nginx
    envFrom:
      - secretRef:
          name: balaji-secret