apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env
spec:
 containers:
   - name: balajibr-env
     image: redis
     env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: third-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
             name: third-secret
             key: password