apiVersion: v1
kind: Service 
metadata:
  name: test2-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      nodePort: 30005
      port: 80
  
  selector: 
        app: app
        balaji: balaji