apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: my-first-cronjob
spec:
  schedule: "45 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: busybox
            command: ["/bin/sh"]
            args: ["-c","date; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure
          
    