apiVersion: batch/v1
kind: Job
metadata:
  name: my-first-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox
        command: ["/bin/sh"]
        args: ["-c","echo hello word"]
      restartPolicy: Never