apiVersion: v1
kind: Pod
metadata: 
  name: node-affinity
spec:
  containers:
    - name: balaji-pod
      image: httpd
  affinity:
    nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
             - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - sdd