apiVersion: v1
kind: Service
metadata: 
   name: my-first-svc
   
spec:
  type: NodePort
  ports:
     - targetPort: 80
       port: 80
       nodePort: 30004
  selector:
       env: dev
       type: backend
        


