apiVersion: v1
kind: Pod
metadata:
  name: three-containers
spec:
 containers:
   - name: first-container
     image: nginx
   - name: second-container
     image: mykplabs/kubernetes:nginx
   - name: third-container
     image: busybox
     command:
        - "sleep"
        - "5600"