apiVersion: v1
kind: Pod
metadata:
  name: postgress-app-pod
  labels:
    name: postgress-app-pod
    app: demo-voting-app 
spec:
  containers:
    - name: postgres
      image: kodekloud/examplevotingapp_postgres:v1
    
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"