apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    purpose: study

spec:
  selector:
    matchLabels:
       name: voting-app-pod
       app: demo-voting-app
  replicas: 3
  template:
       metadata:
        name: worker-app-pod
        labels:
          name: voting-app-pod
          app: demo-voting-app 
       spec:
          containers:
             - name: worker-app 
               image: kodekloud/examplevotingapp_vote:v1
        
       

