apiVersion: apps/v1 
kind: Deployment
metadata:
   name: vaidhee-dep

spec:
  selector:
    matchLabels:
        type: frontend
        env: dev
  template:

    metadata:
       name: pongaluu
       labels:
        type: frontend
        env: dev
    spec:
     containers:
      - name: pongaluu
        image: httpd
  replicas: 3
     
          