apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: vaidhee-rs

spec:
  selector:
    matchLabels:
        type: frontend
        env: dev
  template:

    metadata:
       name: pongaluu
       labels:
        type: frontend
        env: dev
    spec:
     containers:
      - name: pongaluu
        image: httpd
  replicas: 3
     
          