apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replication-controller
spec:
  template:
    metadata:
      name: balaji-pod 
      labels:
         reason: study
    spec:
      containers:
        - name: balaji-pod
          image: nginx
  replicas: 3
  selector:
     reason: study
