apiVersion: v1
kind: Pod 
metadata: 
  name: stephe-pod
  labels:
    type: front-end
spec:
 containers:
   - name: stephe-pod
     image: httpd
 securityContext:
    runAsUser: 1000
    capabilities:
       add: ["MAC_ADMIN"]