apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
  labels:
     env: SIT
     use: webserver
spec:
   containers:
          - name: my-second-container
            image: httpd

          - name: my-co-container
            image: redis

