apiVersion: v1
kind: Pod 
metadata:
  name: webapp-color
  labels:
     name: webapp-color
spec:
   containers:
     - name: webapp-color
       image: kodekloud/webapp-color:latest
       envFrom:
         - configMapRef:
             name: balaji
